### ISSUE TITLE
Backend Instrument Gains Comparison

### ISSUE THREAD

**Issue by chris-baur** [chris-baur/graphelier#3]
Create backend service point for getting the gains/losses of an insrument.
Given:
- instruments to get gains for
- current timestamp
- other timestamp to compare with

# Example Response
`                   0: {`
`                           "instrument": "MSFT",`
`                            "unit": 1.03,`
`                            "percentage": 0.32,`
`                    }, 1: { ... }, ...`

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 2 |
| Priority     | High |
| Risk         | Low |

# Subtasks
- [x] implement service point to handle calls
- [x] implement backend logic to query db
- [x] create tests for queries

# User Story #2
